name: zeppelin-dev

volumes:
  home: {}
  untrusted-home: {}
  mysql-data: {}
  redis-data: {}

services:
  nginx:
    build:
      context: ./docker/development/nginx
      args:
        DEVELOPMENT_WEB_PORT: ${DEVELOPMENT_WEB_PORT:?Missing DEVELOPMENT_WEB_PORT}
    ports:
      - "${DEVELOPMENT_WEB_PORT:?Missing DEVELOPMENT_WEB_PORT}:443"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DEVELOPMENT_MYSQL_ROOT_PASSWORD?:Missing DEVELOPMENT_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zeppelin
      MYSQL_USER: zeppelin
      MYSQL_PASSWORD: ${DEVELOPMENT_MYSQL_PASSWORD?:Missing DEVELOPMENT_MYSQL_PASSWORD}
    ports:
      - "127.0.0.1:${DEVELOPMENT_MYSQL_PORT:?Missing DEVELOPMENT_MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --authentication-policy=mysql_native_password

  redis:
    image: redis:8.2.3
    volumes:
      - redis-data:/data

  devenv:
    build: &devenv-build
      context: ./docker/development/devenv
    init: true
    environment:
      DEVELOPMENT_SSH_PASSWORD: ${DEVELOPMENT_SSH_PASSWORD:?Missing DEVELOPMENT_SSH_PASSWORD}
    ports:
      - "127.0.0.1:${DEVELOPMENT_SSH_PORT:?Missing DEVELOPMENT_SSH_PORT}:22"
    volumes:
      - home:/home/dev
      - ./:/workspace/zeppelin
    healthcheck:
      test: ["CMD", "test", "-e", "/run/uid-ready"]
      interval: 30s
      start_period: 30s
      start_interval: 200ms

  # Utility container to run untrusted applications
  # without sharing the main devenv's container and home dir
  untrusted:
    profiles: [manual]
    build: *devenv-build
    volumes:
      - untrusted-home:/home/dev
      - ./:/workspace/zeppelin

  cftunnel:
    profiles: [cftunnel]
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN:-}
