storeDir: .pnpm-store
verifyDepsBeforeRun: false

packages:
  - 'backend'
  - 'shared'
  - 'dashboard'
  - 'config-checker'

allowBuilds:
  bufferutil: true
  esbuild: true
  utf-8-validate: true

minimumReleaseAge: 20160 # in minutes (2 weeks)
minimumReleaseAgeExclude:
  - 'vety'
  - 'knub-command-manager'

overrides:
  # Keep in sync with Vety's discord.js version
  discord.js: "14.23.2"
  discord-api-types: "0.38.30"

catalogs:
  ts6:
    typescript: 6.0.3
  ts7:
    typescript: 7.0.2
